language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t h0neyman/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true h0neyman/docker-react npm run test
